# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---

name: url-action
# yamllint disable-line rule:line-length
description: Check availability of a website useful to tell if gh-pages are enabled by running curl

inputs:
  url:
    required: false
    # yamllint disable-line rule:line-length
    default: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
  process:
    required: false
    default: curl --fail --head

runs:
  using: composite
  steps:
    - run: |
        set -ex
        echo "action=$${{ github.action_ref }}"
        $${{ inputs.process }} "${{ inputs.url }}"
      shell: bash
