# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---

name: curl-action

inputs:
  url:
    required: false
    # yamllint disable-line rule:line-length
    default: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

runs:
  using: composite
  steps:
    - run: |
        set -ex
        curl --version
        curl --fail --head "${{ inputs.url }}"
      shell: bash
