# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---

name: url-action
# yamllint disable-line rule:line-length
description: Check availability of a website useful to tell if gh-pages are enabled by running curl

inputs:
  url:
    required: false
    # yamllint disable-line rule:line-length
    default: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
  process:
    required: false
    default: curl --fail --head

outputs:
  code:
    value: ${{ steps.run.code }}

runs:
  using: composite
  steps:
    - run: >
        [[ ! "${{ github.action_ref }}" =~ "main$" ]]
        || echo "warning: https://github.com/marketplace/actions/url-action# update version" ;
        set -x ;
        ${{ inputs.process }} "${{ inputs.url }}"
        code="$?" ;
        echo "code=${code}" >> $${GITHUB_ENV} ;
        exit ${code}
      shell: bash
