# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: url

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  url:
    runs-on: ubuntu-latest
    steps:
      - uses: rzr/url-action@main
        with:
          url: https://github.com/${{ github.repository }}
