# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: gh-pages

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:

jobs:

  run:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      conclusion: ${{ steps.url-action.conclusion }}
      outcome: ${{ steps.url-action.outcome }}
      code: ${{ steps.url-action.outputs.code }}
    steps:
      - id: url-action
        uses: rzr/url-action@main
        # - run: echo "info: move comment to above line to force upload"

  bypassed:
    runs-on: ubuntu-latest
    needs: run
    if: ${{ needs.run.outputs.conclusion != 'success' }}
    steps:
      - run: |
          echo "log: code=${{ needs.run.outputs.code }}"
          echo "log: outcome=${{ needs.run.outputs.outcome }}"
          echo "log: conclusion=${{ needs.run.outputs.conclusion }}"
          echo "log: result=${{ needs.run.result }}"

  upload:
    runs-on: ubuntu-latest
    needs: run
    if: >-
      ${{ needs.run.outputs.conclusion == 'success' && github.event_name != 'pull_request' }}
    steps:
      - id: build
        run: install -d _site && touch _site/index.html
      - id: upload
        uses: actions/upload-pages-artifact@v3.0.1

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: upload
        uses: actions/deploy-pages@v4.0.5
